apiVersion: v1
kind: Service
metadata:
  name: {{ include "urlmon.fullname" . }}
  labels:
    {{- include "urlmon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "urlmon.selectorLabels" . | nindent 4 }}
